# Generated by Django 5.0.6 on 2024-11-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
